os: linux
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
#  - "3.7"


before_install:
  # gcc (gfortran is not there by default, we install all gcc suit just in case)
  - sudo apt-get install gcc
  - sudo apt-get install gfortran

  # environment variable
  - export KIMPY_DIR=$PWD
  - export KIM_API_VERSION=v2-2.0.0


install:
  # kim-api
  - cd $KIMPY_DIR && cd ..
  - wget http://s3.openkim.org/kim-api/kim-api-$KIM_API_VERSION.txz
  - tar Jxvf kim-api-$KIM_API_VERSION.txz
  - cd kim-api-$KIM_API_VERSION
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - sudo make install
  - sudo ldconfig

  # ase
  - pip install ase


script:
  - cd $KIMPY_DIR
  - pip install -e .
  - cd tests
  - pytest

